name: fase_2
description: "Clean architecture console demo for Fake Store API"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dartz: ^0.10.1
  dio: ^5.9.0

dev_dependencies:
  lints: ^5.0.0
